### PR TITLE
Simpler beam search for now

### PR DESCRIPTION
**Pull request by gpucce**
@Soonhwan-Kwon the idea here is to have a simple beam search with a many less options than the HF one, while keeping the same logic, so we can (hopefully) merge it sooner and work on a better one later. What do you think?  

Close it, modify it or tell me what you would like to change and I do it if you don't like where this goes

### CODE REVIEW

**Comment by gpucce** [comment]
@Soonhwan-Kwon if you think there are too many changes I will revert the last commit, while the first two should allow to run with larger batch sizes, let me know what you prefer!

**Comment by Soonhwan-Kwon** [comment]
> @Soonhwan-Kwon if you think there are too many changes I will revert the last commit, while the first two should allow to run with larger batch sizes, let me know what you prefer!

I agree with your direction, but I need to do some tests of it with newly released checkpoint tonight(this is 7pm in my country) to confirm there is no side effect or did you already tested it?

**Comment by gpucce** [comment]
> > @Soonhwan-Kwon if you think there are too many changes I will revert the last commit, while the first two should allow to run with larger batch sizes, let me know what you prefer!
> I agree with your direction, but I need to do some tests of it with newly released checkpoint tonight(this is 7pm in my country) to confirm there is no side effect or did you already tested it?

Oh ok great, didn't mean to rush at all sorry if I did! Let me know anything that does not work! I will also test it and see how things go. 

I don't know if you saw this https://github.com/LAION-AI/CLIP_benchmark/pull/63 if you find things that improve validation it might be an idea to add them and later I make it work with the rest of the repo!

**Comment by Soonhwan-Kwon** [comment]
I'm middle of comparing the output, and I expect it will be done this weekend.

**Comment by Soonhwan-Kwon** [comment]
It works very well thank you for the PR!

**Pull request merged**
